import{SvelteComponent,append_hydration,attr,children,claim_element,claim_space,claim_text,detach,element,init,insert_hydration,noop,safe_not_equal,space,src_url_equal,text}from"../../web_modules/svelte/internal/index.mjs";function create_fragment(){let d,n,u,q,O,s,h,o,r,W,B,a,P,A,k,f,z,p,v,y,_,w,t,x,C,E,b,m,S,M,F,T,j,D,N,L,R,i,H,I,l,K,$,c,U,V,g;return{c(){d=element("section"),n=element("div"),u=element("img"),O=space(),s=element("div"),h=element("div"),o=element("h1"),r=element("div"),W=text("0"),B=space(),a=element("div"),P=text("Days"),A=text(`
          To Christmas`),k=space(),f=element("h1"),z=space(),p=element("h2"),v=element("i"),y=text("Silly Season H5P Advent Calendar"),_=element("br"),w=space(),t=element("p"),x=text("Dear All, "),C=element("br"),E=element("br"),b=text(`

        To count down to the holidays and raise a smile, I’ve put together this
        virtual `),m=element("span"),S=text("H5P Advent Calendar"),M=text(` with festive fun, silly, sweet
        and interesting video clips and songs. I’ve set it so you can open them
        all in one sitting or come back each day (or so) to open the next one/s
        as per tradition :).`),F=element("br"),T=element("br"),j=text(`
        Merry wishes!`),D=element("br"),N=element("br"),L=text(`

        Rowena`),R=space(),i=element("a"),H=text("H5P Advent Calendar"),I=space(),l=element("img"),$=space(),c=element("img"),V=space(),g=element("div"),this.h()},l(e){d=claim_element(e,"SECTION",{class:!0});var U,K,q,Y,G,X,Q,Z,J,ne=children(d),ee,te;n=claim_element(ne,"DIV",{class:!0}),K=children(n),u=claim_element(K,"IMG",{src:!0,alt:!0,class:!0}),O=claim_space(K),s=claim_element(K,"DIV",{class:!0}),q=children(s),h=claim_element(q,"DIV",{}),G=children(h),o=claim_element(G,"H1",{class:!0,id:!0}),Y=children(o),r=claim_element(Y,"DIV",{class:!0,id:!0}),X=children(r),W=claim_text(X,"0"),X.forEach(detach),B=claim_space(Y),a=claim_element(Y,"DIV",{class:!0,id:!0}),Q=children(a),P=claim_text(Q,"Days"),Q.forEach(detach),A=claim_text(Y,`
          To Christmas`),Y.forEach(detach),k=claim_space(G),f=claim_element(G,"H1",{class:!0,id:!0}),children(f).forEach(detach),G.forEach(detach),z=claim_space(q),p=claim_element(q,"H2",{}),Z=children(p),v=claim_element(Z,"I",{}),J=children(v),y=claim_text(J,"Silly Season H5P Advent Calendar"),J.forEach(detach),Z.forEach(detach),_=claim_element(q,"BR",{}),w=claim_space(q),t=claim_element(q,"P",{class:!0}),U=children(t),x=claim_text(U,"Dear All, "),C=claim_element(U,"BR",{}),E=claim_element(U,"BR",{}),b=claim_text(U,`

        To count down to the holidays and raise a smile, I’ve put together this
        virtual `),m=claim_element(U,"SPAN",{class:!0}),ee=children(m),S=claim_text(ee,"H5P Advent Calendar"),ee.forEach(detach),M=claim_text(U,` with festive fun, silly, sweet
        and interesting video clips and songs. I’ve set it so you can open them
        all in one sitting or come back each day (or so) to open the next one/s
        as per tradition :).`),F=claim_element(U,"BR",{}),T=claim_element(U,"BR",{}),j=claim_text(U,`
        Merry wishes!`),D=claim_element(U,"BR",{}),N=claim_element(U,"BR",{}),L=claim_text(U,`

        Rowena`),U.forEach(detach),R=claim_space(q),i=claim_element(q,"A",{href:!0,target:!0,rel:!0,class:!0}),te=children(i),H=claim_text(te,"H5P Advent Calendar"),te.forEach(detach),q.forEach(detach),I=claim_space(K),l=claim_element(K,"IMG",{src:!0,alt:!0,class:!0}),$=claim_space(K),c=claim_element(K,"IMG",{src:!0,alt:!0,class:!0}),V=claim_space(K),g=claim_element(K,"DIV",{class:!0}),children(g).forEach(detach),K.forEach(detach),ne.forEach(detach),this.h()},h(){src_url_equal(u.src,q="media/img/santa.png")||attr(u,"src",q),attr(u,"alt","sanata"),attr(u,"class","home__img"),attr(r,"class","home__number"),attr(r,"id","number-data"),attr(a,"class","home__text"),attr(a,"id","text-data"),attr(o,"class","home__title"),attr(o,"id","title-data"),attr(f,"class","home__title"),attr(f,"id","msg-christmas"),attr(m,"class","svelte-10xn6vr"),attr(t,"class","home__description"),attr(i,"href","https://h5p.org/content-types/advent-calendar"),attr(i,"target","_blank"),attr(i,"rel","noopener"),attr(i,"class","button"),attr(s,"class","home__data"),src_url_equal(l.src,K="media/img/bell.png")||attr(l,"src",K),attr(l,"alt","bell"),attr(l,"class","home__bell"),src_url_equal(c.src,U="media/img/star.png")||attr(c,"src",U),attr(c,"alt","star"),attr(c,"class","home__star"),attr(g,"class","home__blob"),attr(n,"class","home__container container"),attr(d,"class","home")},m(e,U){insert_hydration(e,d,U),append_hydration(d,n),append_hydration(n,u),append_hydration(n,O),append_hydration(n,s),append_hydration(s,h),append_hydration(h,o),append_hydration(o,r),append_hydration(r,W),append_hydration(o,B),append_hydration(o,a),append_hydration(a,P),append_hydration(o,A),append_hydration(h,k),append_hydration(h,f),append_hydration(s,z),append_hydration(s,p),append_hydration(p,v),append_hydration(v,y),append_hydration(s,_),append_hydration(s,w),append_hydration(s,t),append_hydration(t,x),append_hydration(t,C),append_hydration(t,E),append_hydration(t,b),append_hydration(t,m),append_hydration(m,S),append_hydration(t,M),append_hydration(t,F),append_hydration(t,T),append_hydration(t,j),append_hydration(t,D),append_hydration(t,N),append_hydration(t,L),append_hydration(s,R),append_hydration(s,i),append_hydration(i,H),append_hydration(n,I),append_hydration(n,l),append_hydration(n,$),append_hydration(n,c),append_hydration(n,V),append_hydration(n,g)},p:noop,i:noop,o:noop,d(e){e&&detach(d)}}}class Component extends SvelteComponent{constructor(e){super(),init(this,e,null,create_fragment,safe_not_equal,{})}}export default Component