import{SvelteComponent,append_hydration,attr,children,claim_element,claim_space,claim_text,detach,element,init,insert_hydration,noop,safe_not_equal,space,src_url_equal,text}from"../../web_modules/svelte/internal/index.mjs";function create_fragment(){let h,s,m,ne,J,n,r,o,a,X,q,d,V,S,A,p,x,b,g,P,_,w,O,t,C,E,k,j,f,M,F,T,z,D,N,L,R,y,H,I,B,u,$,W,U,K,i,Y,G,l,te,Z,c,ee,Q,v;return{c(){h=element("section"),s=element("div"),m=element("img"),J=space(),n=element("div"),r=element("div"),o=element("h1"),a=element("div"),X=text("0"),q=space(),d=element("div"),V=text("Days"),S=text(`
          To Christmas`),A=space(),p=element("h1"),x=space(),b=element("h2"),g=element("i"),P=text("Silly Season H5P Advent Calendar"),_=space(),w=element("br"),O=space(),t=element("p"),C=text("Dear All, "),E=element("br"),k=element("br"),j=text(`

        To count down to the holidays and raise a smile, I’ve put together this
        virtual `),f=element("span"),M=text("H5P Advent Calendar"),F=text(` with festive fun, silly, sweet
        and interesting video clips and songs. I’ve set it so you can open them
        all in one sitting or come back each day (or so) to open the next one/s
        as per tradition :).`),T=element("br"),z=element("br"),D=text(`
        P.S. I've put together an advent calendar below. Scoll down to see it!
        `),N=element("br"),L=element("br"),R=text(`
        Merry wishes!`),y=element("br"),H=element("br"),I=text(`

        Rowena`),B=space(),u=element("p"),$=text("Click here to find out more about this H5P content type."),W=element("br"),U=element("br"),K=space(),i=element("a"),Y=text("H5P Advent Calendar"),G=space(),l=element("img"),Z=space(),c=element("img"),Q=space(),v=element("div"),this.h()},l(e){h=claim_element(e,"SECTION",{class:!0});var he=children(h),ne,te,oe,se,ae,re,ce,le,ee,de,ie,ue;s=claim_element(he,"DIV",{class:!0}),ne=children(s),m=claim_element(ne,"IMG",{src:!0,alt:!0,class:!0}),J=claim_space(ne),n=claim_element(ne,"DIV",{class:!0}),te=children(n),r=claim_element(te,"DIV",{}),oe=children(r),o=claim_element(oe,"H1",{class:!0,id:!0}),se=children(o),a=claim_element(se,"DIV",{class:!0,id:!0}),ae=children(a),X=claim_text(ae,"0"),ae.forEach(detach),q=claim_space(se),d=claim_element(se,"DIV",{class:!0,id:!0}),re=children(d),V=claim_text(re,"Days"),re.forEach(detach),S=claim_text(se,`
          To Christmas`),se.forEach(detach),A=claim_space(oe),p=claim_element(oe,"H1",{class:!0,id:!0}),children(p).forEach(detach),oe.forEach(detach),x=claim_space(te),b=claim_element(te,"H2",{}),ce=children(b),g=claim_element(ce,"I",{}),le=children(g),P=claim_text(le,"Silly Season H5P Advent Calendar"),le.forEach(detach),ce.forEach(detach),_=claim_space(te),w=claim_element(te,"BR",{}),O=claim_space(te),t=claim_element(te,"P",{class:!0}),ee=children(t),C=claim_text(ee,"Dear All, "),E=claim_element(ee,"BR",{}),k=claim_element(ee,"BR",{}),j=claim_text(ee,`

        To count down to the holidays and raise a smile, I’ve put together this
        virtual `),f=claim_element(ee,"SPAN",{class:!0}),de=children(f),M=claim_text(de,"H5P Advent Calendar"),de.forEach(detach),F=claim_text(ee,` with festive fun, silly, sweet
        and interesting video clips and songs. I’ve set it so you can open them
        all in one sitting or come back each day (or so) to open the next one/s
        as per tradition :).`),T=claim_element(ee,"BR",{}),z=claim_element(ee,"BR",{}),D=claim_text(ee,`
        P.S. I've put together an advent calendar below. Scoll down to see it!
        `),N=claim_element(ee,"BR",{}),L=claim_element(ee,"BR",{}),R=claim_text(ee,`
        Merry wishes!`),y=claim_element(ee,"BR",{}),H=claim_element(ee,"BR",{}),I=claim_text(ee,`

        Rowena`),ee.forEach(detach),B=claim_space(te),u=claim_element(te,"P",{}),ie=children(u),$=claim_text(ie,"Click here to find out more about this H5P content type."),W=claim_element(ie,"BR",{}),U=claim_element(ie,"BR",{}),ie.forEach(detach),K=claim_space(te),i=claim_element(te,"A",{href:!0,target:!0,rel:!0,class:!0}),ue=children(i),Y=claim_text(ue,"H5P Advent Calendar"),ue.forEach(detach),te.forEach(detach),G=claim_space(ne),l=claim_element(ne,"IMG",{src:!0,alt:!0,class:!0}),Z=claim_space(ne),c=claim_element(ne,"IMG",{src:!0,alt:!0,class:!0}),Q=claim_space(ne),v=claim_element(ne,"DIV",{class:!0}),children(v).forEach(detach),ne.forEach(detach),he.forEach(detach),this.h()},h(){src_url_equal(m.src,ne="media/img/santa.png")||attr(m,"src",ne),attr(m,"alt","sanata"),attr(m,"class","home__img"),attr(a,"class","home__number"),attr(a,"id","number-data"),attr(d,"class","home__text"),attr(d,"id","text-data"),attr(o,"class","home__title"),attr(o,"id","title-data"),attr(p,"class","home__title"),attr(p,"id","msg-christmas"),attr(f,"class","svelte-10xn6vr"),attr(t,"class","home__description"),attr(i,"href","https://h5p.org/content-types/advent-calendar"),attr(i,"target","_blank"),attr(i,"rel","noopener"),attr(i,"class","button"),attr(n,"class","home__data"),src_url_equal(l.src,te="media/img/bell.png")||attr(l,"src",te),attr(l,"alt","bell"),attr(l,"class","home__bell"),src_url_equal(c.src,ee="media/img/star.png")||attr(c,"src",ee),attr(c,"alt","star"),attr(c,"class","home__star"),attr(v,"class","home__blob"),attr(s,"class","home__container container"),attr(h,"class","home")},m(e,ee){insert_hydration(e,h,ee),append_hydration(h,s),append_hydration(s,m),append_hydration(s,J),append_hydration(s,n),append_hydration(n,r),append_hydration(r,o),append_hydration(o,a),append_hydration(a,X),append_hydration(o,q),append_hydration(o,d),append_hydration(d,V),append_hydration(o,S),append_hydration(r,A),append_hydration(r,p),append_hydration(n,x),append_hydration(n,b),append_hydration(b,g),append_hydration(g,P),append_hydration(n,_),append_hydration(n,w),append_hydration(n,O),append_hydration(n,t),append_hydration(t,C),append_hydration(t,E),append_hydration(t,k),append_hydration(t,j),append_hydration(t,f),append_hydration(f,M),append_hydration(t,F),append_hydration(t,T),append_hydration(t,z),append_hydration(t,D),append_hydration(t,N),append_hydration(t,L),append_hydration(t,R),append_hydration(t,y),append_hydration(t,H),append_hydration(t,I),append_hydration(n,B),append_hydration(n,u),append_hydration(u,$),append_hydration(u,W),append_hydration(u,U),append_hydration(n,K),append_hydration(n,i),append_hydration(i,Y),append_hydration(s,G),append_hydration(s,l),append_hydration(s,Z),append_hydration(s,c),append_hydration(s,Q),append_hydration(s,v)},p:noop,i:noop,o:noop,d(e){e&&detach(h)}}}class Component extends SvelteComponent{constructor(e){super(),init(this,e,null,create_fragment,safe_not_equal,{})}}export default Component